### ISSUE TITLE
Since the new upadte, the teleportation mods are broken, also I recommend making, "Wall Run" so that you have to hold grip to enable the actual wall running part.

### ISSUE THREAD

**Issue by ContagiousRat** [KyleTheScientist/Bark#13]

**Comment by ContagiousRat** [comment]
Since the new updatee, the teleportation mods are broken, also I recommend making, "Wall Run" so that you have to hold grip to enable the actual wall running part.

**Comment by ContagiousRat** [comment]
and btw noclip is also broke

**Comment by developer9998** [comment]
These most likely have been fixed by Kyle

**Comment by KyleTheScientist** [comment]
Fixed in 1.3.1
