### ISSUE TITLE
i can't open menu

### ISSUE THREAD

**Issue by Leosensey** [KyleTheScientist/Bark#15]
i hitting myself with controllers like a flash, but menu is not opening

**Comment by corndogricecake** [comment]
same with me i tried installing other versions to and it didnt work

**Comment by PeanutButterOfficial** [comment]
I have the same problem. None of the gestures open the menu for me.

**Comment by KyleTheScientist** [comment]
There are a few things that could be wrong causing the menu not to open. 

Check that:
* You have the latest Computer Interface installed if Bark.1.3.2.CI is installed
* You have the latest Utilla
* You do **not** have TMP Loader installed (it's broken)
* You're opening the menu in a modded lobby
* You are alternating hands while beating your chest. The gesture expects you to hit 4 times, left-right-left-right or right-left-right-left.

If you have the Computer Interface build installed, you can change the "Open Menu" action from the chest beat gesture to a button press. This might help you more confidently test it.
