### ISSUE TITLE
Bark doesn't work when your banned

### ISSUE THREAD

**Issue by AmongusR** [KyleTheScientist/Bark#17]
2 Days ago, I got banned for 8 weeks because i showed little kids that i had, and used computer interface in a city non-modded lobby and according to them, its "illegal." so when i got banned, i decided I would try the bark mod menu, but when i got it, it turns out it didnt work because i was banned. can u pls fix this issue? thanks!

**Comment by developer9998** [comment]
This isn't an issue. The mod ONLY works in lobbies under the Modded gamemode, since you're banned you can not join any rooms and therefor you can't use Bark.

**Comment by KyleTheScientist** [comment]
As dev mentioned, the mod is not meant to be used offline. 

I'm also pretty sure you can't get banned for 8 weeks just by having one lobby of people report you. Even getting caught by anti-cheat cheats is only a 4 week ban. You must've had multiple serious offenses. 

Anyway, closing this.
