### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by cjbsavage** [KyleTheScientist/Bark#2]
When using no-clip, the platform will teleport you to a invisible block and get you stuck. Not sure if this is just for me, just wanted to put it out there :)

**Comment by KyleTheScientist** [comment]
I've had something similar occur in the past but couldn't recreate it. The quick fix is to just disable and then re-enable the mod in computer interface.

If you can describe how to recreate this issue I'll address it ASAP. 

Things to consider:
* Which map were you playing on? 
* Had you used platforms beforehand?
* Were you using platforms when you enabled no collide?
* What other buttons did you have enabled?
* What other mods did you have installed?

**Comment by cjbsavage** [comment]
It was a normal modded lobby. It does it every where. It does it when trying to no clip and use the platforms. I had no other platform mod installed.

**Comment by KyleTheScientist** [comment]
Does this occur every time or was this a one-time issue?

**Comment by cjbsavage** [comment]
Every time

**Comment by cjbsavage** [comment]
Is this fixed?

**Comment by KyleTheScientist** [comment]
I've recieved a report that this is still an issue in 1.1.2. I suspect this may be an issue with the platforms initializing at the 0,0,0 coordinates and somehow the player gets dragged out there with them when no collide is enabled. I'm hoping the changes to the initialization process in 1.2.0 will fix this.

**Comment by KyleTheScientist** [comment]
Haven't heard any news on this since 1.2.1 released. Closing for now.
