### ISSUE TITLE
buttons, or grabbing is not working. (pls read comment)

### ISSUE THREAD

**Issue by thegoodman1** [KyleTheScientist/Bark#20]
so in the newest gorilla tag update buttons, or grabbing the menu is not working. so can you fix that please? also can you add more mods that lets other normal monkeys mess with the Modder please? those mods are the mods that i have fun with the most! (:

**Comment by redpikachu500** [comment]
same issue

**Comment by KyleTheScientist** [comment]
This should be fixed as of 1.3.3
