### ISSUE TITLE
I know this isn't really an issue but how do I add mods?

### ISSUE THREAD

**Issue by bubzilla** [KyleTheScientist/Bark#33]
I know this isn't really an issue but how do I add mods?

**Comment by LutraVibes** [comment]
You need to use the Monkey Mod Manager. I recommend installing the Computer Interface (CI), Utilla, and TMP Loader mods. Auros and Exinject will come with the CI mod. Once you have it installed, go into your BepInEx folder, go to plugins, and simply drop the Bark mod right into there.

**Comment by bubzilla** [comment]
no like to the actual mod menu
