### ISSUE TITLE
ONE HANDED PLEASE

### ISSUE THREAD

**Issue by levikokokokokok** [KyleTheScientist/Bark#6]
My only problem with this menu is that you need 2 working controllers so pretty please make a 1 handed version

**Comment by KyleTheScientist** [comment]
As much as I would like to set up accessibility features for this mod, I don't see it happening in the near future. Much of the mod relies on having two hands to perform the different gestures and the amount of effort to change that is daunting to say the least. 

I'll leave this issue open, and if more people request this feature I'll consider it at a later date.

**Comment by monke6678** [comment]
on the computer interface you can change the button to open the bark mod. i changed it to left joystick

**Comment by KyleTheScientist** [comment]
Resolved in 1.3.0 with the introduction of CI keybindings
